spring:
  application:
    name: tsumiki-backend
  
  datasource:
    url: jdbc:postgresql://postgres:5432/tsumiki_db
    username: tsumiki_user
    password: tsumiki_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080

logging:
  level:
    com.tsumiki: DEBUG
    org.springframework.web: DEBUG
