name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Run backend tests
      run: |
        cd backend
        ./gradlew test build

  frontend-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Type check
      run: |
        cd frontend
        npm run typecheck
    
    - name: Run tests
      run: |
        cd frontend
        npm test
    
    - name: Build
      run: |
        cd frontend
        npm run build

  lsp-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Serena MCP container
      run: |
        docker compose --profile mcp build serena-mcp
    
    - name: Check LSP binaries
      run: |
        docker run --rm tsumiki_sample-serena-mcp node -v && \
        docker run --rm tsumiki_sample-serena-mcp npm -v && \
        docker run --rm tsumiki_sample-serena-mcp which typescript-language-server && \
        docker run --rm tsumiki_sample-serena-mcp java -version && \
        docker run --rm tsumiki_sample-serena-mcp which kotlin-language-server
